### ISSUE TITLE
ionic sass variable: Undefined variable: "$item-ios-paragraph-text-color"

### ISSUE THREAD

**Issue by msio777** [Urigo/Ionic2CLI-Meteor-WhatsApp#55] opened 2017-02-13 10:48 UTC
Hi,
I'm using tsconfig.json config and webpack of this project and I want to use ionic sass variable in one of my pages. I get  after runnning ionic serve: `Undefined variable "$..."`.  is there problem with some tsconfig property ?

Thanks for any help

**Comment by Slavrix** [comment] 2017-02-15 07:51
have you imported the ionic variables correctly into the file that you are trying to edit the value from ?

**Comment by msio777** [comment] 2017-02-15 15:54
I don't get it, It's working right konw and I didn't change anything :-) thanks for the answer

**Comment by DAB0mB** [comment] 2017-02-15 16:56
@msio777 I'm glad the problem is solved. It can happen that problems "magically" solve themselves and it is something developers share in common from time to time. I'm closing this issue.

**Closed by DAB0mB** 2017-02-15 16:56 UTC
