### ISSUE TITLE
Getting white screen after splash screen in IOS 10.3, working fine on IOS 11

### ISSUE THREAD

**Issue by paduchurikowsik** [Urigo/Ionic2CLI-Meteor-WhatsApp#170] opened 2017-11-07 14:24 UTC
Hello guys,
I am having an issues with the app on IOS 10.3, the app displays white screen after splash screen not matter how much time went. The app is working fine and good on IOS 11. Don't have any idea on what the issue was. I also tried creating a new ionic meteor app but still having the same issue. I would appreciate if anyone can help me with this, thank you.

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : ios 4.5.3
    Ionic Framework    : ionic-angular 3.8.0

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.0.0 
    Node       : v6.11.2
    npm        : 3.10.10 
    OS         : macOS Sierra
    Xcode      : Xcode 9.0 Build version 9A235 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy

**Comment by darkbasic** [comment] 2017-11-07 15:11
I think this is a duplicate of this bug: https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/124

**Closed as completed by darkbasic** 2017-11-07 15:11 UTC
